#!/bin/bash -x

set -e

./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment zlib 1.2.11
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment bzip2 1.0.8
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment zstd 1.5.0
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment brotli 1.0.9
## libffi wants this version
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment gnu-config cci.20201022
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment gnu-config cci.20210814
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment libffi 3.4.2
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment pcre 8.45
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment pcre2 10.37
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment expat 2.4.1
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment openssl 1.1.1l
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment double-conversion 3.1.6
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment libpng 1.6.37
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment libjpeg 9d
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment freetype 2.11.1
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment m4 1.4.18
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment m4 1.4.19
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment autoconf 2.71
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment libelf 0.8.13
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment libiconv 1.16
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment libgettext 0.20.1
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment ninja 1.10.2
## these are build requirements and all must be installed
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment meson 0.59.1
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment meson 0.59.2
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment meson 0.60.1
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment meson 0.60.2
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment pkgconf 1.7.4
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment libmount 2.36.2
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment flex 2.6.4
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment libselinux 3.3
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment \
--require-override 'libselinux/3.3@' \
glib 2.70.1
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment \
--require-override 'freetype/2.11.1@' \
--require-override 'glib/2.70.1@' \
--require-override 'libselinux/3.3@' \
harfbuzz 3.1.2
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment sqlite3 3.37.0
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment opengl system
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment \
--require-override 'openssl/1.1.1l@' \
cmake 3.22.0
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment --local-recipe=../conan-center-index/recipes/nodejs/all nodejs 16.3.0
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment bison 3.7.1
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment bison 3.7.6
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment gperf 3.1
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment automake 1.16.4
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment libtool 2.4.6
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment libuuid 1.0.3
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment --require-override 'freetype/2.11.1@' fontconfig 2.13.93
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment icu 70.1
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment xorg system
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment libxml2 2.9.12
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment wayland 1.19.0
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment wayland-protocols 1.21
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment xkbcommon 1.3.1
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment opus 1.3.1
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment xorg-macros 1.19.3
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment xorg-proto 2021.4
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment libxshmfence 1.3
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment nspr 4.32
./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment --require-override 'sqlite3/3.37.0@' nss 3.72

./local_equivalent.py --platform debian_bullseye_gcc10_armv7hf --build-types Release --additional-profiles-for-all-platforms qt-options-linux --configuration-branch=qt_experiment \
  --require-override 'freetype/2.11.1@' \
  --require-override 'openssl/1.1.1l@' \
  --require-override 'double-conversion/3.1.6@' \
  --require-override 'icu/70.1@' \
  --require-override 'harfbuzz/3.1.2@' \
  --require-override 'glib/2.70.1@' \
  --require-override 'cmake/3.22.0@' \
  --require-override 'libselinux/3.3@' \
  --require-override 'sqlite3/3.37.0@' \
  --require-override 'xkbcommon/1.3.1@' \
qt 6.2.2
