#!/bin/bash -x 

set -e
export LOCAL_PLATFORM=centos7_gcc10
export COMMON_ARGUMENTS="--platform $LOCAL_PLATFORM --build-types Release --configuration-branch=qt_experiment"
export CONAN_SYSREQUIRES_MODE=enabled

sudo yum install -y which
rm -rf ~/.conan

./local_equivalent.py $COMMON_ARGUMENTS zlib 1.2.11
./local_equivalent.py $COMMON_ARGUMENTS bzip2 1.0.8
./local_equivalent.py $COMMON_ARGUMENTS zstd 1.5.2
./local_equivalent.py $COMMON_ARGUMENTS brotli 1.0.9

./local_equivalent.py $COMMON_ARGUMENTS gnu-config cci.20201022
./local_equivalent.py $COMMON_ARGUMENTS gnu-config cci.20210814
./local_equivalent.py $COMMON_ARGUMENTS libffi 3.4.2
./local_equivalent.py $COMMON_ARGUMENTS pcre 8.45
./local_equivalent.py $COMMON_ARGUMENTS pcre2 10.37

./local_equivalent.py $COMMON_ARGUMENTS expat 2.4.4
./local_equivalent.py $COMMON_ARGUMENTS expat 2.4.6
./local_equivalent.py $COMMON_ARGUMENTS openssl 1.1.1m
./local_equivalent.py $COMMON_ARGUMENTS openssl 3.0.1
./local_equivalent.py $COMMON_ARGUMENTS double-conversion 3.2.0
./local_equivalent.py $COMMON_ARGUMENTS libpng 1.6.37

./local_equivalent.py $COMMON_ARGUMENTS libjpeg 9d
./local_equivalent.py $COMMON_ARGUMENTS freetype 2.11.1
./local_equivalent.py $COMMON_ARGUMENTS m4 1.4.19
./local_equivalent.py $COMMON_ARGUMENTS autoconf 2.69
./local_equivalent.py $COMMON_ARGUMENTS autoconf 2.71

./local_equivalent.py $COMMON_ARGUMENTS libelf 0.8.13
./local_equivalent.py $COMMON_ARGUMENTS libiconv 1.16
./local_equivalent.py $COMMON_ARGUMENTS libgettext 0.20.1
./local_equivalent.py $COMMON_ARGUMENTS ninja 1.10.2
# # glib wants 0.59.1
./local_equivalent.py $COMMON_ARGUMENTS meson 0.59.1
./local_equivalent.py $COMMON_ARGUMENTS meson 0.59.2
./local_equivalent.py $COMMON_ARGUMENTS meson 0.59.3
./local_equivalent.py $COMMON_ARGUMENTS meson 0.60.2

./local_equivalent.py $COMMON_ARGUMENTS pkgconf 1.7.4
./local_equivalent.py $COMMON_ARGUMENTS flex 2.6.4

./local_equivalent.py $COMMON_ARGUMENTS glib 2.70.1

./local_equivalent.py $COMMON_ARGUMENTS harfbuzz 3.2.0

./local_equivalent.py $COMMON_ARGUMENTS --local-recipe=../conan-ccdcsqlite3 ccdcsqlite3 3.38.0

./local_equivalent.py $COMMON_ARGUMENTS sqlite3 3.38.0

./local_equivalent.py $COMMON_ARGUMENTS opengl system
./local_equivalent.py $COMMON_ARGUMENTS --local-recipe=../conan-xorg xorg system

./local_equivalent.py $COMMON_ARGUMENTS --require-override 'openssl/1.1.1m@' cmake 3.21.4
./local_equivalent.py $COMMON_ARGUMENTS --require-override 'openssl/1.1.1m@' cmake 3.22.0

./local_equivalent.py $COMMON_ARGUMENTS nodejs 16.3.0
./local_equivalent.py $COMMON_ARGUMENTS bison 3.7.6
./local_equivalent.py $COMMON_ARGUMENTS gperf 3.1

./local_equivalent.py $COMMON_ARGUMENTS automake 1.16.4
./local_equivalent.py $COMMON_ARGUMENTS libtool 2.4.6
./local_equivalent.py $COMMON_ARGUMENTS libuuid 1.0.3

./local_equivalent.py $COMMON_ARGUMENTS libxml2 2.9.12

./local_equivalent.py $COMMON_ARGUMENTS --require-override 'expat/2.4.6@' wayland 1.20.0

./local_equivalent.py $COMMON_ARGUMENTS wayland-protocols 1.24


./local_equivalent.py $COMMON_ARGUMENTS xkbcommon 1.3.1

./local_equivalent.py $COMMON_ARGUMENTS --require-override 'expat/2.4.6@' dbus 1.12.20

./local_equivalent.py $COMMON_ARGUMENTS fontconfig 2.13.93

./local_equivalent.py $COMMON_ARGUMENTS icu 70.1

./local_equivalent.py $COMMON_ARGUMENTS opus 1.3.1
   
./local_equivalent.py $COMMON_ARGUMENTS nspr 4.32

./local_equivalent.py $COMMON_ARGUMENTS --local-recipe=../conan-nss nss 3.76

./local_equivalent.py $COMMON_ARGUMENTS vulkan-headers 1.2.198.0
./local_equivalent.py $COMMON_ARGUMENTS vulkan-loader 1.2.198.0

time ./local_equivalent.py $COMMON_ARGUMENTS --configuration-local-directory ../conan-ccdc-common-configuration --local-recipe=../conan-qt qt 5.15.8

time ./local_equivalent.py $COMMON_ARGUMENTS --configuration-local-directory ../conan-ccdc-common-configuration --local-recipe=../conan-qwt qwt 6.2.0
# time ./local_equivalent.py $COMMON_ARGUMENTS --configuration-local-directory ../conan-ccdc-common-configuration \
#   --local-recipe=../conan-ccdc-main \
#   ccdc-main 2022.2.0
