#!/bin/bash -x 

set -e

./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment zlib 1.2.11
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment bzip2 1.0.8
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment zstd 1.5.1
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment brotli 1.0.9

./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment gnu-config cci.20201022
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment gnu-config cci.20210814
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment libffi 3.4.2
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment pcre 8.45
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment pcre2 10.37

./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment expat 2.4.3
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment openssl 1.1.1m
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment openssl 3.0.1
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment double-conversion 3.1.7
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment libpng 1.6.37

./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment libjpeg 9d
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment freetype 2.11.1
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment m4 1.4.19
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment autoconf 2.69
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment autoconf 2.71

./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment libelf 0.8.13
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment libiconv 1.16
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment libgettext 0.20.1
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment ninja 1.10.2
# # glib wants 0.59.1
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment meson 0.59.1
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment meson 0.59.2
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment meson 0.60.2

./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment pkgconf 1.7.4
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment flex 2.6.4

./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment glib 2.70.1

./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment harfbuzz 3.2.0

./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment sqlite3 3.37.2
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment opengl system

./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment \
   --require-override 'openssl/1.1.1m@' \
cmake 3.21.4
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment \
   --require-override 'openssl/1.1.1m@' \
cmake 3.22.0
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment nodejs 16.3.0
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment bison 3.7.6
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment gperf 3.1

./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment automake 1.16.4
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment libtool 2.4.6
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment libuuid 1.0.3
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment \
   --require-override 'expat/2.4.3@' \
 fontconfig 2.13.93
./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment icu 70.1
time ./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment --configuration-local-directory ../conan-ccdc-common-configuration \
  --local-recipe=../conan-center-index/recipes/qt/6.x.x \
  qt 6.2.2

./local_equivalent.py --platform macos11_xcode13_arm --build-types Release --additional-profiles-for-all-platforms qt-options-macos --configuration-branch=qt_experiment --configuration-local-directory ../conan-ccdc-common-configuration \
  --local-recipe=../conan-qt \
  qttestpkg 0.1
