parameters:
  - name: package
    type: string
  - name: package_version
    type: string
  - name: user
    type: string
    default: ccdc
  - name: channel
    type: string
    default: testing
  - name: build_types
    type: object
    default:
      - Release
      - Debug
      - RelWithDebInfo
  - name: source_repository
    type: string
    default: public-conan-center
  - name: destination_repository
    type: string
    default: ccdc-3rdparty-conan
  - name: platforms
    type: object
    default:
      - centos7_gcc9
      - ubuntu2004_gcc10
      - macos1015_xcode11
      - win2016_vs2017
      - win2019_vs2019
  - name: macos_brew_preinstall
    type: object
    default: []
  - name: macos_deployment_target
    type: string
    default: '10.13'
  - name: windows_bash_path
    type: string
    default: 'NOT VALID UNLESS SET, ONLY USED BY WINDOWS BUILDS'
  - name: conan_logging_level
    type: string
    default: 'critical'

jobs:
- ${{ if containsValue(parameters.platforms, 'centos7_gcc9') }}:
  - job: centos7_gcc9
    pool:
      vmImage: "ubuntu-latest"
    # We use a container to run the build as we must be compatible with centos7's older glibc
    container: rockdreamer/centos7-gcc9:latest
    steps:
      # No need to setup specific python, the container's python3 will be used
      - template: single-build.yml@templates
        parameters:
          python: 'python3'
          package: ${{ parameters.package }}
          package_version: ${{ parameters.package_version }}
          user: ${{ parameters.user }}
          channel: ${{ parameters.channel }}
          profile: centos7-gcc9-x86_64
          build_types: ${{ parameters.build_types }}
          source_repository: ${{ parameters.source_repository }}
          destination_repository: ${{ parameters.destination_repository }}
          conan_logging_level: ${{ parameters.conan_logging_level }}

- ${{ if containsValue(parameters.platforms, 'ubuntu2004_gcc10') }}:
  - job: ubuntu2004_gcc10
    pool:
      vmImage: "ubuntu-latest"
    # We use a container to run the build as we must be compatible with centos7's older glibc
    container: rockdreamer/ubuntu20-gcc10:latest
    steps:
      # No need to setup specific python, the container's python3 will be used
      - template: single-build.yml@templates
        parameters:
          python: 'python3'
          package: ${{ parameters.package }}
          package_version: ${{ parameters.package_version }}
          user: ${{ parameters.user }}
          channel: ${{ parameters.channel }}
          profile: ubuntu20-gcc10-x86_64
          build_types: ${{ parameters.build_types }}
          source_repository: ${{ parameters.source_repository }}
          destination_repository: ${{ parameters.destination_repository }}
          conan_logging_level: ${{ parameters.conan_logging_level }}

- ${{ if containsValue(parameters.platforms, 'macos1015_xcode11') }}:
  - job: macos1015_xcode11
    pool:
      vmImage: "macOS-latest"
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8"
        displayName: "Use latest python 3.8"
      - ${{ each preinstall_pkg in parameters.macos_brew_preinstall }}: # package
        - task: CmdLine@2
          inputs:
            script: "brew install ${{ preinstall_pkg }}"
          displayName: "Brew install ${{ preinstall_pkg }}"

      - template: single-build.yml@templates
        parameters:
          python: 'python'
          package: ${{ parameters.package }}
          package_version: ${{ parameters.package_version }}
          user: ${{ parameters.user }}
          channel: ${{ parameters.channel }}
          profile: macos-xcode11-x86_64
          build_types: ${{ parameters.build_types }}
          source_repository: ${{ parameters.source_repository }}
          destination_repository: ${{ parameters.destination_repository }}
          macos_deployment_target: ${{ parameters.macos_deployment_target }}
          conan_logging_level: ${{ parameters.conan_logging_level }}

- ${{ if containsValue(parameters.platforms, 'win2016_vs2017') }}:
  - job: win2016_vs2017
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - task: PowerShell@2
        displayName: "Nuke useless tools"
        inputs:
          targetType: 'inline'
          script: |
            # Makes removal faster
            $chocolibs = ('OpenSSL.Light', 'mingw')
            foreach($chocolib in $chocolibs) {
              if (Test-Path "$env:ChocolateyInstall\lib\$chocolib") {
                Move-Item "$env:ChocolateyInstall\lib\$chocolib" -Destination "C:\removed-$chocolib" -Force
              }
            }
            $chocoexes = (
              'addr2line.exe',
              'ar.exe',
              'as.exe',
              'c++.exe',
              'c++filt.exe',
              'cc1.exe',
              'cc1plus.exe',
              'collect2.exe',
              'cpp.exe',
              'elfedit.exe',
              'f951.exe',
              'fixincl.exe',
              'g++.exe',
              'gcc-ar.exe',
              'gcc-nm.exe',
              'gcc-ranlib.exe',
              'gcc.exe',
              'gdb.exe',
              'gdbmtool.exe',
              'gdbm_dump.exe',
              'gdbm_load.exe',
              'gdborig.exe',
              'gdbserver.exe',
              'gfortran.exe',
              'ld.bfd.exe',
              'ld.exe',
              'ld.gold.exe',
              'lto-wrapper.exe',
              'lto1.exe',
              'make.exe',
              'mingw32-make.exe',
              'mingw64-pkg.bat',
              'nm.exe',
              'objcopy.exe',
              'objdump.exe',
              'ranlib.exe',
              'readelf.exe',
              'x86_64-w64-mingw32-c++.exe',
              'x86_64-w64-mingw32-g++.exe',
              'x86_64-w64-mingw32-gcc-8.1.0.exe',
              'x86_64-w64-mingw32-gcc-ar.exe',
              'x86_64-w64-mingw32-gcc-nm.exe',
              'x86_64-w64-mingw32-gcc-ranlib.exe',
              'x86_64-w64-mingw32-gcc.exe',
              'x86_64-w64-mingw32-gfortran.exe'
            )
            foreach($chocoexe in $chocoexes) {
              if (Test-Path "$env:ChocolateyInstall\bin\$chocoexe") {
                Remove-Item "$env:ChocolateyInstall\bin\$chocoexe" -Force
              }
            }
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8"
        displayName: "Use latest python 3.8"
      - template: single-build.yml@templates
        parameters:
          python: 'python'
          package: ${{ parameters.package }}
          package_version: ${{ parameters.package_version }}
          user: ${{ parameters.user }}
          channel: ${{ parameters.channel }}
          profile: windows-msvc15-amd64
          build_types: ${{ parameters.build_types }}
          source_repository: ${{ parameters.source_repository }}
          destination_repository: ${{ parameters.destination_repository }}
          conan_logging_level: ${{ parameters.conan_logging_level }}

- ${{ if containsValue(parameters.platforms, 'win2019_vs2019') }}:
  - job: win2019_vs2019
    pool:
      vmImage: "windows-2019"
    steps:
      - task: PowerShell@2
        displayName: "Nuke useless tools"
        inputs:
          targetType: 'inline'
          script: |
            # Makes removal faster
            $chocolibs = ('OpenSSL.Light', 'mingw')
            foreach($chocolib in $chocolibs) {
              if (Test-Path "$env:ChocolateyInstall\lib\$chocolib") {
                Move-Item "$env:ChocolateyInstall\lib\$chocolib" -Destination "C:\removed-$chocolib" -Force
              }
            }
            $chocoexes = (
              'addr2line.exe',
              'ar.exe',
              'as.exe',
              'c++.exe',
              'c++filt.exe',
              'cc1.exe',
              'cc1plus.exe',
              'collect2.exe',
              'cpp.exe',
              'elfedit.exe',
              'f951.exe',
              'fixincl.exe',
              'g++.exe',
              'gcc-ar.exe',
              'gcc-nm.exe',
              'gcc-ranlib.exe',
              'gcc.exe',
              'gdb.exe',
              'gdbmtool.exe',
              'gdbm_dump.exe',
              'gdbm_load.exe',
              'gdborig.exe',
              'gdbserver.exe',
              'gfortran.exe',
              'ld.bfd.exe',
              'ld.exe',
              'ld.gold.exe',
              'lto-wrapper.exe',
              'lto1.exe',
              'make.exe',
              'mingw32-make.exe',
              'mingw64-pkg.bat',
              'nm.exe',
              'objcopy.exe',
              'objdump.exe',
              'ranlib.exe',
              'readelf.exe',
              'x86_64-w64-mingw32-c++.exe',
              'x86_64-w64-mingw32-g++.exe',
              'x86_64-w64-mingw32-gcc-8.1.0.exe',
              'x86_64-w64-mingw32-gcc-ar.exe',
              'x86_64-w64-mingw32-gcc-nm.exe',
              'x86_64-w64-mingw32-gcc-ranlib.exe',
              'x86_64-w64-mingw32-gcc.exe',
              'x86_64-w64-mingw32-gfortran.exe'
            )
            foreach($chocoexe in $chocoexes) {
              if (Test-Path "$env:ChocolateyInstall\bin\$chocoexe") {
                Remove-Item "$env:ChocolateyInstall\bin\$chocoexe" -Force
              }
            }
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8"
        displayName: "Use latest python 3.8"
      - template: single-build.yml@templates
        parameters:
          python: 'python'
          package: ${{ parameters.package }}
          package_version: ${{ parameters.package_version }}
          user: ${{ parameters.user }}
          channel: ${{ parameters.channel }}
          profile: windows-msvc16-amd64
          build_types: ${{ parameters.build_types }}
          source_repository: ${{ parameters.source_repository }}
          destination_repository: ${{ parameters.destination_repository }}
          conan_logging_level: ${{ parameters.conan_logging_level }}
